GET http://localhost:3000/users

###
GET http://localhost:3000/users/1

###
POST http://localhost:3000/users/
Content-Type: application/json

{
   "id":"1",
    "name": "Davied",
    "isStudent": false
}
###
PUT http://localhost:3000/users/_l7otr0fg5
Content-Type: application/json

{
    "id":"_ewspg0bjs",
    "name": "Yassen",
    "isStudent": true   
}


###
DELETE http://localhost:3000/users/_l7otr0fg5

